tokens = {
   "pw":"white pawn",
   "nw":"white knight",
   "bw":"white bishop",
   "rw":"white rook",
   "qw":"white queen",
   "kw":"white king",
   "pb":"black pawn",
   "nb":"black knight",
   "bb":"black bishop",
   "rb":"black rook",
   "qb":"black queen",
   "kb":"black king",
   "pwm":"white pawn potential move",
   "nwm":"white knight potential move",
   "bwm":"white bishop potential move",
   "rwm":"white rook potential move",
   "qwm":"white queen potential move",
   "kwm":"white king potential move",
   "pbm":"black pawn potential move",
   "nbm":"black knight potential move",
   "bbm":"black bishop potential move",
   "rbm":"black rook potential move",
   "qbm":"black queen potential move",
   "kbm":"black king potential move",
   "50m":"fifty move rule",
   "3f":"three fold rule",
   "qpm":"queen pawn promotion",
   "npm":"knight pawn promotion",
   "rpm":"rook pawn promotion",
   "bpm":"biship pawn promotion",
   "SEP":"seperation token (SPECIAL)",
   "MASK":"token used for masking (SPECIAL)",
   "PAD":"token used for padding (SPECIAL)"
}